### ISSUE TITLE
Organização Dos arquivos

### ISSUE THREAD

**Issue by Joao620** [ArqueologiaDigital/Mines#1]
queria começar essa thread aqui para decidir como vai ficar a organização de arquivos, onde vão ficar o código especifico de cada plataforma e onde ficaria o código compartilhado

Só para iniciar, eu vou dar uma estrutura super básica para ser evoluída e discutida.

plataformas/
├─ Commodore64/
├─ Core/ /* aqui onde ficaria o código compartilhado */
├─ MSX2/

não tenho tanto conhecimento com compilação em C e sdcc para saber se o Core pode ser facilmente importado para a compilação das plataformas

**Comment by felipesanches** [comment]
Esbocei agora algo parecido com isso que você descreveu. 
Fiz assim:
![Screenshot from 2022-05-28 16-36-20](https://user-images.githubusercontent.com/213676/170840428-6cd6f315-5e2d-4671-b461-dc6375f332e6.png)

Nesse commit inicial criei um Makefile para a plataforma **ncurses** (pra eu poder testar o programa nativamente no terminal do meu Debian GNU+Linux). Sugiro criar outros Makefiles para cada uma das demais plataformas.
