### ISSUE TITLE
[MSX] ASlink-Warning-Undefined Global '_putchar' referenced by module 'vprintf'

### ISSUE THREAD

**Issue by felipesanches** [ArqueologiaDigital/Mines#7]
@pvmm:
![Screenshot from 2022-05-30 05-16-03](https://user-images.githubusercontent.com/213676/170948695-e24fdcc1-e9e5-406d-a798-8b7ee02ae4a2.png)

**Comment by pvmm** [comment]
PR #8 solves this.
